# Generated by Django 4.2.16 on 2026-05-27 18:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('accounts', '0001_initial'),
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('upload', 'File Uploaded'), ('parse_complete', 'Parse Completed'), ('approve', 'Record Approved'), ('reject', 'Record Rejected'), ('edit', 'Record Edited'), ('flag', 'Record Flagged'), ('unflag', 'Record Unflagged'), ('add_note', 'Note Added'), ('scope_change', 'Scope/Category Changed')], max_length=30)),
                ('old_values', models.JSONField(default=dict)),
                ('new_values', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('datasource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='ingestion.datasource')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.organization')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='emissions.emissionrecord')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['organization', 'timestamp'], name='audit_audit_organiz_47f094_idx'), models.Index(fields=['record', 'timestamp'], name='audit_audit_record__4aa621_idx')],
            },
        ),
    ]
