# Generated by Django 4.2.16 on 2026-05-27 18:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(blank=True, choices=[('scope_1', 'Scope 1 — Direct emissions'), ('scope_2', 'Scope 2 — Purchased electricity/heat'), ('scope_3', 'Scope 3 — Value chain & travel')], max_length=10)),
                ('category', models.CharField(choices=[('diesel', 'Diesel fuel'), ('petrol', 'Petrol / Gasoline'), ('natural_gas', 'Natural gas'), ('lpg', 'LPG'), ('other_fuel', 'Other fuel'), ('electricity', 'Electricity'), ('flight', 'Flight'), ('hotel', 'Hotel'), ('ground_transport', 'Ground transport'), ('rail', 'Rail'), ('procurement', 'Procurement'), ('unknown', 'Unknown — needs classification')], default='unknown', max_length=30)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('activity_period_end', models.DateField(blank=True, help_text='For billing periods that span multiple days (e.g. utility bills).', null=True)),
                ('source_row_data', models.JSONField(help_text='Original row from source file, verbatim. Never modified.')),
                ('source_row_number', models.IntegerField(help_text='Row number in original file (1-indexed after header).')),
                ('raw_quantity', models.FloatField(blank=True, null=True)),
                ('raw_unit', models.CharField(blank=True, max_length=50)),
                ('normalized_quantity', models.FloatField(blank=True, null=True)),
                ('normalized_unit', models.CharField(blank=True, max_length=50)),
                ('emission_factor', models.FloatField(blank=True, help_text='kg CO2e per normalized_unit. Locked at ingestion time.', null=True)),
                ('emission_factor_source', models.CharField(blank=True, help_text="Source standard and year, e.g. 'DESNZ 2023' or 'ICAO 2023 + RFI'.", max_length=100)),
                ('co2e_kg', models.FloatField(blank=True, help_text='kg CO2e = normalized_quantity × emission_factor. Only for approved records.', null=True)),
                ('location', models.CharField(blank=True, help_text='Plant code, meter address, hotel, or city.', max_length=255)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('origin', models.CharField(blank=True, help_text='Airport IATA code', max_length=10)),
                ('destination', models.CharField(blank=True, help_text='Airport IATA code', max_length=10)),
                ('flight_class', models.CharField(blank=True, max_length=20)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_review', max_length=20)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reasons', models.JSONField(default=list, help_text='List of flag reason strings from parser + manual flags.')),
                ('analyst_notes', models.TextField(blank=True, help_text='Free-text notes added by analyst during review.')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='accounts.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to='accounts.userprofile')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.datasource')),
            ],
            options={
                'ordering': ['-activity_date', 'source'],
                'indexes': [models.Index(fields=['organization', 'status'], name='emissions_e_organiz_a7c7c2_idx'), models.Index(fields=['organization', 'scope'], name='emissions_e_organiz_cfc59b_idx'), models.Index(fields=['organization', 'activity_date'], name='emissions_e_organiz_143c84_idx'), models.Index(fields=['source', 'status'], name='emissions_e_source__f4e6f7_idx')],
            },
        ),
    ]
