# Generated by Django 4.2.16 on 2026-05-27 18:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Flat File (MB51/ME2M)'), ('UTILITY', 'Utility Portal CSV'), ('TRAVEL', 'Travel Platform CSV (Navan/Concur)')], max_length=10)),
                ('name', models.CharField(help_text='Human-readable name for this upload, set by user.', max_length=255)),
                ('raw_file', models.FileField(help_text='Original file preserved for audit and re-parsing.', upload_to='uploads/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('parsed_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('flagged_rows', models.IntegerField(default=0)),
                ('field_mapping_override', models.JSONField(default=dict, help_text='Per-upload custom field mapping overrides.')),
                ('parse_log', models.JSONField(default=list)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasources', to='accounts.organization')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
